BEGIN;

DROP TABLE IF EXISTS refunds;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS seat_showtimes;
DROP TABLE IF EXISTS showtimes;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS studio_seat;
DROP TABLE IF EXISTS studios;
DROP TABLE IF EXISTS cinemas;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS client_users;

COMMIT;
